### ISSUE TITLE
pegamoid, deprecated np.float

### ISSUE THREAD

**Issue by ptrab** [Nix-QChem/NixOS-QChem#297]
Hi :)

when we are executing pegamoid with `LD_LILRBARY_PATH= nixGL nix run github:Nix-QChem/NixOS-QChem#pegamoid` we get the following message across our computers.

```
warning: Using saved setting for 'allow-import-from-derivation = true' from ~/.local/share/nix/trusted-settings.json.
warning: Using saved setting for 'extra-substituters = https://nix-qchem.cachix.org' from ~/.local/share/nix/trusted-settings.json.
Traceback (most recent call last):
  File "/nix/store/r1d2wfnvmjf3k13nmg1sz6wf0jb8pzpq-Pegamoid-2.6.2/bin/..pegamoid.py-wrapped-wrapped", line 7585, in <module>
    win = MainWindow()
  File "/nix/store/r1d2wfnvmjf3k13nmg1sz6wf0jb8pzpq-Pegamoid-2.6.2/bin/..pegamoid.py-wrapped-wrapped", line 2890, in __init__
    self.init_VTK()
  File "/nix/store/r1d2wfnvmjf3k13nmg1sz6wf0jb8pzpq-Pegamoid-2.6.2/bin/..pegamoid.py-wrapped-wrapped", line 3623, in init_VTK
    self.lut.SetTableRange(-np.finfo(np.float).eps, np.finfo(np.float).eps)
  File "/nix/store/b7kiy1c75f7f3lvg05qm913k17f8gdn4-python3.10-numpy-1.24.2/lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?

```

Is this only something, the pegamoid developers can fix (because it seems that they did not change their `np.float` to `float`), or do you see a way to fix it with a patch within NixOS-QChem?

All the best
Philipp

**Comment by sheepforce** [comment]
This is probably resolved by Pegamoid 2.8. Will take care of it when coming back from vacation next week. For the moment you could use an older version without the breaking numpy changes, e.g.

```
nix run github:Nix-QChem/NixOS-QChem?rev=b6c23828758fdda3d7f857918650e00abc4c95ec#pegamoid
```
