### ISSUE TITLE
python3.biopython broken on nixpkgs master

### ISSUE THREAD

**Issue by markuskowa** [Nix-QChem/NixOS-QChem#575]
Broke with the latest staging-next update.

```
Running phase: buildPhase
Executing pypaBuildPhase
Creating a wheel...
* Getting build dependencies for wheel...
Traceback (most recent call last):
  File "/nix/store/c8vrsk4fk6sgyapybzwc4964milsnb2d-python3.11-pyproject-hooks-1.2.0/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
    main()
  File "/nix/store/c8vrsk4fk6sgyapybzwc4964milsnb2d-python3.11-pyproject-hooks-1.2.0/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in main
    json_out["return_val"] = hook(**hook_input["kwargs"])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/c8vrsk4fk6sgyapybzwc4964milsnb2d-python3.11-pyproject-hooks-1.2.0/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 143, in get_requires_for_build_wheel
    return hook(config_settings)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/m2ywgq0byidd245mrks7qcw3i9zh0a4k-python3.11-setuptools-75.1.0/lib/python3.11/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=[])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/m2ywgq0byidd245mrks7qcw3i9zh0a4k-python3.11-setuptools-75.1.0/lib/python3.11/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
    self.run_setup()
  File "/nix/store/m2ywgq0byidd245mrks7qcw3i9zh0a4k-python3.11-setuptools-75.1.0/lib/python3.11/site-packages/setuptools/build_meta.py", line 503, in run_setup
    super().run_setup(setup_script=setup_script)
  File "/nix/store/m2ywgq0byidd245mrks7qcw3i9zh0a4k-python3.11-setuptools-75.1.0/lib/python3.11/site-packages/setuptools/build_meta.py", line 318, in run_setup
    exec(code, locals())
  File "<string>", line 42, in <module>
  File "<string>", line 42, in <genexpr>
ValueError: invalid literal for int() with base 10: 'post0'

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel
```

**Comment by sheepforce** [comment]
Hm, fails even on master and from a quick look I can't find that `post0` anywhere. I will open an upstream nixpkgs bug.

**Comment by sheepforce** [comment]
https://github.com/NixOS/nixpkgs/issues/353639

**Comment by markuskowa** [comment]
I did not realise it is an upstream package...
